[package]
name = "rtcping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stderrlog = "0.5.1"
log = "0.4"
structopt = "0.3.25"